# Generated by Django 5.0 on 2023-12-05 11:13

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Udokike Daniel', max_length=50)),
                ('image', models.ImageField(upload_to='Uploads/')),
                ('youtube_video_link', embed_video.fields.EmbedVideoField(help_text='Enter the video url here', max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
