# Generated by Django 5.0 on 2023-12-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(default='Maker', max_length=50),
            preserve_default=False,
        ),
    ]
